### ISSUE TITLE
ScalaProjectConfigurator should sort .classpath entries

### ISSUE THREAD

**Issue by ghost** [sonatype/m2eclipse-scala#10]
David:

currently, presentation order of .classpath entries in eclipse after 
"Maven -> Update Project ..." is random, since ScalaProjectConfigurator 
just add entries and does not do any sorting;

this is rather annoying, since every time you run update,
you get a new layout :-)

instead, with alphabetical sorting activated, it should be:

src/main/java
src/main/scala
src/main/resources
src/test/java
src/test/scala
src/test/resources

thank you,

Andrei

**Comment by davidB** [comment]
Hi Andrei,

Can you try version 0.4.0 ?
This version doesn't sort in alphabetical order, but should sort always in the same order (contribution from http://github.com/germanklf)

Sorry for late reply.
