### ISSUE TITLE
Cannot install Maven Integration for Scala IDE 0.4.0

### ISSUE THREAD

**Issue by christian-schlichtherle** [sonatype/m2eclipse-scala#13]
I have Eclipse 3.7.2 with Scala IDE 2.0.1. When I try to install Maven Integration for Scala IDE 0.4.0 from http://alchim31.free.fr/m2e-scala/update-site/ I get the following error message:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.maven.ide.eclipse.scala,0.4.0
No repository found containing: org.eclipse.update.feature,org.maven.ide.eclipse.scala_feature,0.4.0

Am I doing something wrong?

**Comment by mpiggott** [comment]
Perhaps ask the owner of the update site?  As far as I'm aware we don't offer one, you'd need to build this project locally.

**Comment by davidB** [comment]
Can you try : http://alchim31.free.fr/m2e-scala/update-site/m2eclipse-scala/site.xml ?

**Comment by christian-schlichtherle** [comment]
Sorry, but I gave up on this tool chain. NetBeans + Scala plugin works out of the box and seems to be integrated well.
