### ISSUE TITLE
Update site unavailable and no download for version 0.4.0

### ISSUE THREAD

**Issue by erikrozendaal** [sonatype/m2eclipse-scala#14]
When I try to access the update site (http://alchim31.free.fr/m2e-scala/update-site) the connection hangs and times out. There is also no download for 0.4.0 in the downloads tab. 

Finally, building locally (MacOS X) with mvn 3.0.3 gives me an internal maven error currently and I'd really prefer to use the update site.

**Comment by davidB** [comment]
Do you have the same issue when you try to access it via web browser ?
I didn't have the issue, I'll try after a remove.

**Comment by davidB** [comment]
Can you try http://alchim31.free.fr/m2e-scala/update-site/m2eclipse-scala/site.xml ?
The main update site agregate m2e-scala and http://download.eclipse.org/technology/m2e/releases (you can be long to respond)

**Comment by erikrozendaal** [comment]
Update site seems to work again. Thanks! Any chance of adding m2e-scala to the scala-IDE update site or eclipse marketplace? We had some terrible performance issues due to scala-library being in the maven class path compiler and it would be good if it was clearer that m2e-scala solves this problem..

**Comment by davidB** [comment]
Hi,

3 years ago, there was a discussion between  sonatype and scala-ide team about hosting of the plugin without "ready to use solution". It's why I host the update-site.

About referencing the plugin into eclipse-marketplace or m2e connector, it require some work currently not on my todo list (patch, instructions welcome)

About the performance issue, I was not aware about it (as I always have m2e-scala ;-) ). May be a comment on the ml or wiki of scala-ide is a good way to start.

Thanks for your comments.
