### ISSUE TITLE
Should use the scala library that is specified in the pom

### ISSUE THREAD

**Issue by trajano** [sonatype/m2eclipse-scala#20]
I noticed that the Scala version being used is the one that comes with the bundle rather than the one provided by the POM.  This yields an error when using Akka Actors 2.1-M1 which uses 2.10 of Scala.  Ideally it would already be part of Maven dependencies so the scala libraries should not need to be loaded separately.

**Comment by davidB** [comment]
Hi,

I would like but it's not possible. Scala-IDE require to use the same version of scala into the compiler, the library and the plugin.

see http://scala-ide.org/docs/user/faq.html.

Sorry you will have to several eclipse+scala installation (once per scala version)
