### ISSUE TITLE
Modules dependencies not refreshed when editing parent pom

### ISSUE THREAD

**Issue by slandelle** [sonatype/m2eclipse-scala#21]
Upgrade a version in the parent dependencyManagement doesn't upgrade modules dependencies, even when using "Update Project".

The only way I could find to update the modules is to remove them from workspace, remove all .setting, .classpath, .project files and re-import them.

I tested tons of different combinations between eclipse (indigo vs juno), scala IDE (2.0.2 vs nightly), m2e (1.0.2 vs 1.1.0) and it never works properly. The only constant is the m2e-scala-plugin, as only 0.4.1 is available on the update-site.

**Comment by slandelle** [comment]
Tracking the culprit down: building m2e-scala manually, starting from what seems to be last commit for 0.4.0.
Dependency resolution works again with 6060527bbef67519fb5b75a64b49c349c0932e4d (tested with indigo).

Yay!

**Comment by davidB** [comment]
Hi,

I did some clean in the plugin (master), and after I tried to change in my clone of gatling (Stephane's project) the slf4.version then call "update Project" on the parent (+ recursive) I the content of Maven Dependencies container was updated.

Can you confirm ? (then I'll release the 0.5.0)

**Comment by slandelle** [comment]
Yep, I confirm that the Maven libraries get now refreshed. I tested with m2e 1.1.0 (can't upgrade to 1.20 because of buildhelper integration).

Thanks!
