### ISSUE TITLE
Importing Tycho test plugin pom

### ISSUE THREAD

**Issue by satyagraha** [sonatype/m2eclipse-scala#28]
I have developed an Eclipse plugin with separate test plugin in the usual way for Tycho. What I'd like to do is write the tests in Scala (using ScalaTest). However, when I try to import the tests plugin pom with:

```
<packaging>eclipse-test-plugin</packaging>
```

then none of the specified Scala source folders are recognized (even the default ones).
If I change the packaging to `jar`, then everything works correctly.

I can do a `mvn clean package` from the parent command line and all is fine, including compiling and running ScalaTests.

Any clues on what to do?

**Comment by davidB** [comment]
No idea, I never used this packaging.

Sorry

**Comment by satyagraha** [comment]
On further investigation, it appears that there is an entry `source.. = somedir/` in the file `build.properties` which this packaging expects, and this entry appears to override what is specified in the `pom.xml` during the import process. However, they both must specify the same path if the codebase is to behave the same in Eclipse and when driven directly from Maven.

I'm not sure whether this is relevant to your work so I am closing the issue.
