### ISSUE TITLE
scala-swing missing from classpath after updating to Scala IDE 4.0.0.m2

### ISSUE THREAD

**Issue by norru** [sonatype/m2eclipse-scala#29]
After updating to 4.0.0.m2 "scala-swing" has disappeared from the Scala Library container in Eclipse Project

/opt/eclipse-dist/eclipse_scala_4.3/plugins/org.scala-lang.scala-library_2.10.4.v20140209-180020-VFINAL-b66a39653b.jar
/opt/eclipse-dist/eclipse_scala_4.3/plugins/org.scala-lang.scala-reflect_2.10.4.v20140209-180020-VFINAL-b66a39653b.jar
/opt/eclipse-dist/eclipse_scala_4.3/plugins/org.scala-lang.scala-actors_2.10.4.v20140209-180020-VFINAL-b66a39653b.jar

scala-swing is present in the pom but it doesn't get imported in the Maven container (a quick look at the m2e scala source code show that it is removed)

```
    <dependency>
        <groupId>org.scala-lang</groupId>
        <artifactId>scala-swing</artifactId>
        <version>${scala.version}</version>
        <scope>compile</scope>
    </dependency>
```

where scala.version=2.10.4

**Comment by davidB** [comment]
scala-swing, scala-library, scala-dbc are removed from Maven container, because there are provided by Scala-IDE plugin. They should match the scala's version of Scala-IDE plugin.

**Comment by norru** [comment]
That's what I thought - unfortunately in 4.0.0.m2 scala-swing appears to
have disappeared.

On 9 June 2014 16:55, David Bernard notifications@github.com wrote:

> scala-swing, scala-library, scala-dbc are removed from Maven container,
> because there are provided by Scala-IDE plugin. They should match the
> scala's version of Scala-IDE plugin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sonatype/m2eclipse-scala/issues/29#issuecomment-45507176
> .

## 

Cheers,
Nico

**Comment by norru** [comment]
Are you guys in contact with the main Scala-IDE team?

On 9 June 2014 16:59, Nicola Orrù nigu.orru@gmail.com wrote:

> That's what I thought - unfortunately in 4.0.0.m2 scala-swing appears to
> have disappeared.
> 
> On 9 June 2014 16:55, David Bernard notifications@github.com wrote:
> 
> > scala-swing, scala-library, scala-dbc are removed from Maven container,
> > because there are provided by Scala-IDE plugin. They should match the
> > scala's version of Scala-IDE plugin.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sonatype/m2eclipse-scala/issues/29#issuecomment-45507176
> > .
> 
> ## 
> 
> Cheers,
> Nico

## 

Cheers,
Nico

**Comment by davidB** [comment]
May it's an issue on Scala-IDE, else we should know the rule (from us) when
the plugin should "exclude" scala-swing or not.
Try to contact the Scala-IDE team.

**Comment by davidB** [comment]
not since some months.

**Comment by norru** [comment]
Here it is:
https://www.assembla.com/spaces/scala-ide/support/tickets/1002154-scala-swing-missing-from-classpath-after-updating-to-scala-ide-4-0-0-m2#/activity/ticket:
