### ISSUE TITLE
sample project "prj-scala-only" compilation failure

### ISSUE THREAD

**Issue by aroyc** [sonatype/m2eclipse-scala#31]
while issuing the command:
$mvn -X clean install
Getting the following error (some sequence of snaps is attached)

![screenshot from 2014-09-01 00 28 18](https://cloud.githubusercontent.com/assets/6095769/4102881/04fede70-3141-11e4-9c16-ddd7c5dccdd7.png)
![screenshot from 2014-09-01 00 28 30](https://cloud.githubusercontent.com/assets/6095769/4102879/04da1612-3141-11e4-8e94-479573cb7645.png)
![screenshot from 2014-09-01 00 28 37](https://cloud.githubusercontent.com/assets/6095769/4102878/04d82956-3141-11e4-9b99-15f95121da2b.png)
![screenshot from 2014-09-01 00 28 43](https://cloud.githubusercontent.com/assets/6095769/4102880/04df607c-3141-11e4-99d7-ba97c44c53ca.png)

**Comment by davidB** [comment]
It's the expected behavior, because "pending" is not supported by JUnit (search pending in http://doc.scalatest.org/1.7.1/org/scalatest/junit/JUnitSuite.html)

It also help to check that test failed when expected ;-)

**Comment by aroyc** [comment]
Thanks!

**Comment by aroyc** [comment]
But then how to compile the samples given here ?

**Comment by davidB** [comment]
The sample compile and failed as expected. It's a demo. You can remove the pending test.

**Comment by aroyc** [comment]
Oh Thanks!

On Thu, Sep 4, 2014 at 4:10 PM, David Bernard notifications@github.com
wrote:

> The sample compile and failed as expected. It's a demo. You can remove the
> pending test.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sonatype/m2eclipse-scala/issues/31#issuecomment-54450390
> .

## 

Regards,

ARGHYA ROY CHAUDHURI
Dept. of EE
IISc
Bangalore - 560012
Mob: +91-96326-88-010
