### ISSUE TITLE
update 0.4.3 -> 0.5.0 breaks m2e 1.5 and 1.6 on eclipse 4.3 and 4.4

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sonatype/m2eclipse-scala#35]
description:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=446748

possible reason: pull request https://github.com/sonatype/m2eclipse-scala/pull/34

**Comment by Andrei-Pozolotin** [comment]
I verified by private build  from commit https://github.com/sonatype/m2eclipse-scala/commit/cc32ef1cb65c1faf4f9b29c365e3265fe9af2408
that reverting back to 0.4.3 does resolve the `ConcurrentModificationException` issue.

**Comment by davidB** [comment]
I remove use of Job. You can give a try to version 0.5.1
(re-open the ticket, if the issue persist)

**Comment by Andrei-Pozolotin** [comment]
yes, 0.5.1 resolves the issue. thank you.
